name: evented_bloc
description: An extension to the bloc state management library which adds
  support for firing outgoing events from blocs to external listeners.
version: 0.0.1
repository: https://github.com/jovazcode/evented_bloc
topics:
  [
    bloc,
    events-streaming,
    outgoing-events,
    temporary-states
  ]

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  meta: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0

screenshots:
  - description: The evented bloc package logo.
    path: screenshots/logo.png
